config/routes.rb
Rails.application.routes.draw do
  get 'landing/index'

  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :landing
  resources :home do
    resources :posts
  end
  resources :posts do
      resources :comments
  end
  resources :sessions
  get 'prog/testing', :to => 'home#testing'
  root 'landing#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
    validates_uniqueness_of :email
    has_many :posts, dependent: :destroy
    # has_many :model, :dependent => :delete_all 
    mount_uploader :image, ImageUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, counter_cache: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :account
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_account
        @current_account ||= Account.find(session[:id]) if session[:id]
    end
      helper_method :current_account
      
      def authorize
        redirect_to '/'
      end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    skip_before_action :verify_authenticity_token
    def show
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
    end
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
            if @comment.save
                render json: {
                    message: "success",
                }
            end
            
      end
     
      def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        if @comment.destroy
            render json: {
                message: "deleted",
                :bago => @comment
            }
        end
      end

    private
        def comment_params
            params.require(:comment).permit(:email, :laman, :acctid)
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :verify_authenticity_token
    #require 'moment'
    def self.search(search)
        if search
          where('title LIKE ?', "%#{title}%").paginate(:per_page => 10, :page => params[:page]).order('posts.created_at DESC')
        else
            render json: {
                message: "f"
            } 
        end
        respond_to do |format|
            format.json { render :json => @posts }
            format.html
        end
      end
    def testing
        @accounts = Account.all
        @posts = Post.where('title LIKE ?', "%#{params[:title]}%").order('posts.created_at DESC')
    end
    def index
        # @posts = Post.order('posts.created_at DESC')
        @accounts = Account.all
        @posts = Post.where('title LIKE ?', "%#{params[:title]}%").paginate(:per_page => 10, :page => params[:page]).order('posts.created_at DESC')
        @tops = Post.select("id", "comments_count", "title", "account_id").where("comments_count > ?", 0 ).order("comments_count DESC").limit(3)
        respond_to do |format|
            format.json { render :json => @posts }
            format.html
        end
    end
    def show
        @accounts = Account.all
        @account = Account.find(params[:id])
        @posts = Post.where("account_id = ?", params[:id]).order('posts.created_at DESC')
        user_email = Account.select("email").where("id = ?", params[:id])
        @user_tops = Post.select("id", "comments_count", "title", "account_id").where("account_id = ?", params[:id]).where("comments_count > ?", 0 ).order("comments_count DESC").limit(3)
        @posts.count
    end
    def edit
        @account = Account.find(params[:id])
    end
    def update
        @account = Account.find(params[:id])
       
        if @account.update(account_params) 
            render json: {
                message: "success"
            }
        else
            render json: {
                message: "failed"
            } 
        end
    end
    def destroy
        # @post = Post.find(params[:id])
        # respond_to do |format|
        #     format.json { render :json => @post }
        #     format.html
        # end
        # @post.destroy
        #     render json: {
        #         message: "success"
        #     }
    end
    private
    def account_params
        params.require(:account).permit(:id, :first, :last, :email, :password, :image, :desc)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  skip_before_action :verify_authenticity_token
  def show
  end
  def index
    account = Account.all
  end
  def new
    @signup = Account.new
    end
  def create
    accounts = Account.select("email").all
    @signup = Account.new(account_params)
        if @signup.save
            # UserMailer.signup_confirmation(@signup).deliver
            # session[:id] = @signup.id
            render json: {
                message: "success",
                id:  @signup.id,
                vv: session[:id]
            }
          else
            render json: {
              error_message: "email taken",
              message: "failed"
            }
        end

  end
    private
    def account_params
        params.require(:account).permit(:id, :first, :last, :email, :password, :image, :desc)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    skip_before_action :verify_authenticity_token
    def index
        @post = Post.find(params[:home_id])
        @comments = Comment.where("post_id = ?", params[:home_id]).paginate(:per_page => 10, :page => params[:page])
        @comments.count
        @accounts = Account.select('id', 'image', 'first').all
        @tops = Post.select("id", "comments_count", "title", "account_id").order("comments_count DESC").limit(3)
        respond_to do |format|
            format.json { render :json =>  { :comments => @comments.last,
                                            :acct => @accounts,
                                            :nn => current_account.id }}
            format.html
        end
    end
    def show
        @post = Post.find(params[:home_id])
    end
    def create
        @home = Account.find(params[:home_id])
        @post = @home.posts.create(post_params)
            if @post.save
                render json: {
                    message: "success",
                    status: :ok
                }
            else
                render json: {
                    message: "failed",
                }
            end
            
      end
      def update
        @post = Post.find(params[:id])
       
        if @post.update(post_params) 
            render json: {
                message: "success"
            }
        else
            render json: {
                message: "failed"
            } 
        end
    end
     
      def destroy
        @post = Post.find(params[:id])
            if @post.destroy
                render json: {
                    message: "success"
                }
            else
                render json: {
                    message: "failed"
                }  
        end
      end
    private
        def post_params
            params.require(:post).permit(:email, :title, :content, :image)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def new
  end
  
  def create
    user = Account.find_by_email(params[:email])
    password = Account.find_by_password(params[:password])
    pass = Account.select('password').where("email = ?", params[:email])
    if user && (user.password == password.password)
      session[:id] = user.id
      render json: {
        message: "success",
        username: user.first
      }
    else
      render json: {
        # sa_email: user.password,
        # sa_password: password.password,
        message: "failed"
      }
    end
  end
  
  def destroy
    session[:id] = nil
    redirect_to '/'
  end
  private
    def account_params
        params.require(:account).permit(:id, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/results.html.erb
    <tbody>
        <tr>
            <td>' +v.title+ '</td>
            <td>
                <a href=/home/'+v.id+'/posts class="btn btn-info btn-sm">View Post</a>
            </td>
        </tr>

app/views/home/testing.html.erb
<%
=begin %>
<main role="main" style="margin-top:85px; margin-left:20px">
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 feed">
            <div class="card" style="margin-bottom:15px">
                <div class="view overlay">
                    <%= image_tag @post.image_url.to_s, :class=>"card-img-top", :style=>"width:100%; height:300px"%>
                    <a>
                    <div class="mask rgba-white-slight"></div>
                    </a>
                </div>
                <div class="card-header">
                    <% @accounts.each do |t| %>
                        <% if(@post.account_id === t.id) && t.image_url %>
                            <%= image_tag t.image_url.to_s, :style => "width:50px; height:50px; border-radius: 50%" %>
                            <% elsif(@post.account_id === t.id) && !(t.image_url) %>
                                <%= image_tag 'myAvatar.png', :style => "width:50px; height:50px; border-radius: 50%" %>
                        <% end %>
                    <% end %>
                    <h5 class="font-weight-bold " style="margin-top:-40px; margin-left:55px"> <%= @post.title %> </h5>
                    <span class="badge badge-default position-absolute" style="font-size:10px; font-style:italic; right:0"> <%= @post.created_at.strftime("%D %I:%M %p") %>, <%= @comments.count %> comments <span>
                </div>
                <div class="card-body">
                    <p class="card-text"> <%= @post.content %> </p>
                </div>
            </div>
        </div>
    </div>
</main>
<%
=begin %>
<div class="card" style="margin-bottom:15px">
    <div class="card-header">
        <h4><%= @post.title %></h4>
        <p style="font-size:10px; margin-bottom:-20px; font-style:italic"> <%= @post.created_at.strftime("%D %I:%M %p") %>, <%= @comments.count %> comments <p>
    </div>
    <div class="card-body">
        <blockquote class="blockquote mb-0">
            <p style="font-size:15px"><%= @post.content %></p>
                <% if current_account && current_account.email === @post.email%>
                    <footer class="blockquote-footer"> <cite title="Source Title">My Article</cite></footer>
                <% else %>
                    <footer class="blockquote-footer">
                        Posted by:
                        <% @accounts.each do |acct| %>
                            <% if (@post.account_id === acct.id) && acct.image_url %>
                                <%= image_tag acct.image_url.to_s, :style => "width:35px; height:35px; border-radius: 10%" %>
                            <% elsif(@post.account_id === acct.id) && !(acct.image_url) %>
                                <%= image_tag 'icon.jpg', :style => "width:35px; height:35px; border-radius: 10%" %>
                            <% end %>
                        <% end %>
                        <a style="color:#6C7592" href="/home/<%=@post.account_id%>">
                            <cite title="Source Title">
                                <%= @post.email %>
                            </cite>
                        </a>
                    </footer> 
                <% end %>
        </blockquote>
    </div>
</div>
<% @posts.each do |post| %>
    <div class="articles col-xs-6 col-sm-6 col-md-6 col-lg-12">
        <div class="card wow fadeInDown" style="margin-bottom:15px">
            <div class="card-header">
                <% @accounts.each do |t| %>
                    <% if(post.account_id === t.id) && t.image_url %>
                        <%= image_tag t.image_url.to_s, :style => "width:50px; height:50px; border-radius: 50%" %>
                        
                        <% elsif(post.account_id === t.id) && !(t.image_url) %>
                            <%= image_tag 'myAvatar.png', :style => "width:50px; height:50px; border-radius: 50%" %>
                    <% end %>
                <% end %>
                <a style="font-weight:550; text-decoration:none;" href="/home/<%=post.account_id%> "> <%= post.email %> </a>
                <p class="card-text" style="position:absolute; margin-left:55px; margin-top:-20px; font-size:13px"><small class="text-muted"> <%= time_ago_in_words(post.created_at) %> ago,
                <% if post.comments.size === 0 %>
                    <%= '0 comment' %> </p>
                    <% else %>
                        <%= pluralize post.comments.size, 'comment' %>
                <% end %>
                </small> </p>
            </div>
            <div class="card-body">
                <% if !post.image_url.to_s %>
                <% elsif %>
                    <div class="view overlay">
                        <%= image_tag post.image_url.to_s, :class=>"card-img-top w-responsive"%>
                        <a href="#!">
                        <div class="mask rgba-white-slight"></div>
                        </a>
                    </div>
                <% end %>
                <h5 class="card-title"><%= post.title %></h5>
                <% if post.content.scan(/[\w-]+/).size < 90 %>
                    <p class="card-text"><%= post.content %></p>
                    <% else %>
                        <p id="cont<%=post.id%>" class="long" class="card-text">
                            <%= post.content.truncate_words(90) %> 
                            <a href='#see' class="see" id="cont<%=post.id%>"> see more </a> 
                        </p>
                        <div class="cont" id="cont<%=post.id%>" hidden> 
                            <p id="hide<%=post.id%>">
                                <%= post.content %> <a href='#hide' class="hide" id="hide<%=post.id%>"> see less </a>
                            </p>
                        </div>
                <% end %>
                <% if current_account.id === post.account_id %>
                    <input class="form-control dd" value=<%= post.id %> hidden />  
                    <%= link_to 'Delete', home_posts_path(post), :id =>'delete', :class => "btn btn-danger btn-sm delete",:style => "float:right; margin-left:5px " %>
                <% end %>
                <%= link_to 'Comments', home_posts_path(post), :class => "btn blue-gradient btn-rounded btn-sm", :style => "float:right;" %>
            </div>
        </div>
    </div>
<% end %>
<br>
<br>
<br>
<br>
<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-12 col-lg-7 feed">
        <% @posts.each do |post| %>
            <div class="articles col-xs-6 col-sm-6 col-md-6 col-lg-12">
                <div class="card mb-5">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-6 col-md-6 col-lg-6 col-xl-6">
                                <div class="view overlay z-depth-5" style="margin-top:-40px;">
                                    <% if !post.image_url %>
                                    <% elsif %>
                                        <%= image_tag post.image_url.to_s, :style=>"width:100%; height:100%" %>
                                    <% end %>
                                    <a>
                                        <div class="mask rgba-white-slight"></div>
                                    </a>
                                </div>
                            </div>
                            <span class="badge badge-info position-absolute" style="top:0; right:0"> <%= time_ago_in_words(post.created_at) %> ago </span>
                            <div class="col-sm-6 col-md-6 col-lg-6 col-xl-6">
                                <h4 class="card-title"> <%= post.title %> </h4>
                                <div class="author bg-primary" style="border-radius:20px; width:auto">
                                    <% @accounts.each do |t| %>
                                        <% if(post.account_id === t.id) && t.image_url %>
                                            <%= image_tag t.image_url.to_s, :class=>"rounded-circle img-fluid p-1", :style=>"width:30px; height:30px" %>
                                        <% elsif(post.account_id === t.id) && !(t.image_url) %>
                                            <%= image_tag 'myAvatar.png', :class=>"rounded-circle img-fluid p-1", :style=>"width:30px; height:30px" %>
                                        <% end %>
                                    <% end %>
                                    <a href="/home/<%=post.account_id%>" style="text-decoration:none;" class="text-dark"> <%= post.email %> </a>
                                </div>
                                <hr>
                                <% if post.content.scan(/[\w-]+/).size < 90 %>
                                    <p class="card-text"><%= post.content %></p>
                                    <% else %>
                                        <p id="cont<%=post.id%>" class="long card-text">
                                            <%= post.content.truncate_words(90) %> 
                                            <a href='#see' class="see" id="cont<%=post.id%>"> see more </a> 
                                        </p>
                                        <div class="cont" id="cont<%=post.id%>" hidden> 
                                            <p id="hide<%=post.id%>">
                                                <%= post.content %> <a href='#hide' class="hide" id="hide<%=post.id%>"> see less </a>
                                            </p>
                                        </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                    <div class="ml-n4 mt-n4">
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                                <ul>
                                    <li style="display: inline; list-style: none">
                                        <a href="/home/<%=post.id%>/posts" class="btn btn-unique btn-sm">
                                            <i class="far fa-comments pr-2" aria-hidden="true"></i>
                                            Comments 
                                            <span class="badge badge-pill badge-danger">
                                                <% if post.comments.size === 0 %>
                                                    0
                                                <% else %>
                                                    <%= pluralize post.comments.size, '' %>
                                                <% end %>
                                            </span>
                                        </a>
                                    </li>
                                    <li style="display: inline; list-style: none">
                                        <a href="/home/<%=post.account_id%>" class="btn btn-unique btn-sm">
                                            <i class="fas fa-user-alt pr-2" aria-hidden="true"></i>About the Author
                                        </a>
                                    </li>
                                    <% if current_account.id === post.account_id %>
                                        <li style="display: inline; list-style: none">
                                            <input class="form-control dd" value=<%= post.id %> id="dd" hidden />  
                                            <%= link_to 'Delete', home_posts_path(post), :id =>'delete', :class => "btn btn-unique btn-sm delete"%>
                                        </li>
                                    <% end %>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>
<script>

    $('a#delete').click(function(x){
        x.preventDefault();
        var current = $(this).attr('href');
        var e = $('input#dd').val();
        console.log(current);
        $.ajax({
        method: 'get',
        url: $(this).attr('href'),
        success: function(json){
            console.log(json)
            swal({
            type: "question",
            title: 'Delete this post?',
            showCancelButton: true,
            confirmButtonText: 'Confirm',
            cancelButtonText: 'Cancel',
            preConfirm: () => {
                return json
            }
            }).then(json=>{
            if(json.value){
                console.log(json.value);
                $.ajax({
                    method: 'DELETE',
                    url: '/posts/'+e,
                    data: json.value,
                    success: function(response){
                    if(response.message == 'success'){
                        const toast = Swal.mixin({
                            toast: true,
                            position: 'top-end',
                            showConfirmButton: false,
                        });
                        toast({
                            type: 'success',
                            title: 'Post Deleted'
                        },setTimeout(function() {
                                location.reload();
                            }, 1000))
                        }
                    }
                })
            }
            else{
                }
            });
        }

        })
    })
</script>
=end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'FinLogo.ico' %>
    <title>Forum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

<% 
=begin %> 
  <%= javascript_include_tag('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js') %>
  <%= javascript_include_tag('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js') %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" %>

    <%= stylesheet_link_tag "sweetalert2.min.css" %>
    <%= javascript_include_tag('sweetalert2.all.min.js') %>
    <%= javascript_include_tag('sweetalert2.min.js') %>
    <%= javascript_include_tag('moment.js') %>
    <%= javascript_include_tag('moment.min.js') %>
<% 
=end %>

    <%=stylesheet_link_tag "https://use.fontawesome.com/releases/v5.7.0/css/all.css"%>
    <%=stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css"%>
    <%=stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.4/css/mdb.min.css"%>

    <%=stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.33.1/sweetalert2.css"%>
    <%=stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.33.1/sweetalert2.min.css"%>





    <%=javascript_include_tag("https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.33.1/sweetalert2.all.js")%>
    <%=javascript_include_tag("https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.33.1/sweetalert2.all.min.js")%>


    <%=javascript_include_tag("https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js")%>
    <%=javascript_include_tag("https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js")%>
    <%=javascript_include_tag("https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js")%>
    <%=javascript_include_tag("https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js")%>
    <%=javascript_include_tag("https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.4/js/mdb.min.js")%>
    <%= javascript_include_tag('jquery.min.js') %>

    
     
  <body style="background-color:#DAE0E6">
    <%= yield %>
  </body>
</html>